"""allow overdraft

Revision ID: 5b77643fd154
Revises: e43f3ccb51ca
Create Date: 2026-10-04 01:02:13.771346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b77643fd154'
down_revision: Union[str, Sequence[str], None] = 'e43f3ccb51ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('allow_overdraft', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'allow_overdraft')
    # ### end Alembic commands ###
