"""Added transaction reversals

Revision ID: dadcff0b5c97
Revises: 5b77643fd154
Create Date: 2026-10-05 10:16:56.963630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dadcff0b5c97'
down_revision: Union[str, Sequence[str], None] = '5b77643fd154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('reverses_transaction_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'transactions', ['reverses_transaction_id'])
    op.create_foreign_key(None, 'transactions', 'transactions', ['reverses_transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_column('transactions', 'reverses_transaction_id')
    # ### end Alembic commands ###
